target-version = "py313"
line-length = 100

select = [
    "E",  # Style errors
    "W",  # Style warnings
    "F",  # Pyflakes
    "I",  # isort
    "B",  # Bugbear
    "Q",  # Quotes
    "UP", # pyupgrade
    "S",  # Security
]

ignore = [
    "E501", # Line too long (handled by line-length above)
    "B008", # Function calls in argument defaults
    "S101", # Use of assert
    "S311", # Non-cryptographic random
]

[flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"
avoid-escape = true

[isort]
combine-as-imports = true
force-sort-within-sections = true
